# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'SQLManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SQLManager
  pod 'SQLClient', '~> 1.0.0'
  pod 'SwiftyButton'
  pod 'SnapKit'
  pod 'SpreadsheetView'
  pod 'SwiftAlgorithms'
  
end
